name: Build Extension

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure nuget
        uses: nuget/setup-nuget@v1

      - name: Configure msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Debug: List repository contents
        run: |
          echo "Current Directory: $(Get-Location)"
          dir -Recurse

      - name: Update version
        shell: pwsh
        run: |
          $version = "1.0.$env:GITHUB_RUN_NUMBER"
          Write-Output "Updating version to $version"

          $files = @(
            "MonokaiVibrantAmped/source.extension.vsixmanifest",
            "MonokaiVibrantAmped/Properties/AssemblyInfo.cs",
            "MonokaiVibrantAmped/MonokaiVibrantAmped.cs"
          )

          foreach ($file in $files) {
            if (Test-Path -Path $file) {
              Write-Output "Updating: $file"
              (Get-Content -Path $file) |
                ForEach-Object { $_ -replace '1\.0\.0', $version } |
                Set-Content -Path $file
            } else {
              Write-Warning "File not found: $file"
            }
          }

      - name: Restore
        run: nuget restore

      - name: Build
        run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal

      - uses: actions/upload-artifact@v4
        with:
          name: MonokaiVibrantAmped.vsix
          path: MonokaiVibrantAmped\bin\Release\MonokaiVibrantAmped.vsix
