name: Build Extension

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure nuget
        uses: nuget/setup-nuget@v1

      - name: Configure msbuild
        uses: microsoft/setup-msbuild@v1.3.0

      - name: Update version
        shell: pwsh
        run: |
          $files = @(
              'MonokaiVibrantAmped\source.extension.vsixmanifest',
              'MonokaiVibrantAmped\Properties\AssemblyInfo.cs'
              'MonokaiVibrantAmped\MonokaiVibrantAmped.cs'
          )
          foreach ($file in $files) {
              if (Test-Path -Path $file) {
                  $content = Get-Content -Path $file
                  $updated = $content | ForEach-Object { $_ -Replace '1.0.0', "1.0.$env:GITHUB_RUN_NUMBER" }
                  Set-Content -Path $file -Value $updated -NoNewline
              } else {
                  Write-Warning "File not found: $file"
              }
          }

      - name: Restore
        run: nuget restore

      - name: Build
        run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal

      - uses: actions/upload-artifact@v4
        with:
          name: MonokaiVibrantAmped.vsix
          path: MonokaiVibrantAmped\bin\Release\MonokaiVibrantAmped.vsix
